import { roboto } from '@/public/fonts/Roboto'
import type { Metadata } from 'next'
import MyProvider from './Home/page'
import './globals.scss'

export const metadata: Metadata = {
	title: 'Madsoft',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={roboto.className}>
				<MyProvider>{children}</MyProvider>
			</body>
		</html>
	)
}
